---
activation-options:
  debug: false
  deploy_elb: true
  deploy_edns: true
  deploy_k8s_master: true
  deploy_k8s_worker: true
vm:
  vagrant_runtime_directory: /vagrant/.runtime
k8s-clusters:
  regions: ["us-east"]
  number_of_elbs_per_region: 1
  number_of_ednss_per_region: 1
  number_of_clusters_per_region: 1
  number_of_azs_per_region: 3
  master_nodes_per_cluster: 3
  worker_nodes_per_cluster: 0
  number_ip_addresses_reserved_per_cluster: 5
elb-vm:
  vagrant-box: ubuntu/focal64
  virtualbox:
    gui: true
    memory: 2048
    cpus: 1
edns-vm:
  vagrant-box: ubuntu/focal64
  virtualbox:
    gui: true
    memory: 2048
    cpus: 1
k8s-master-vm:
  vagrant-box: ubuntu/focal64
  virtualbox:
    gui: true
    memory: 4096
    cpus: 2
k8s-worker-vm:
  vagrant-box: ubuntu/focal64
  virtualbox:
    gui: true
    memory: 4096
    cpus: 2
