---
# Under development - not operational
virtual-resource-provider:
  # virtualbox (implemented) (not implemented: hyper-v, azure, aws, gcp)
  technology-product: virtualbox
vagrant-config:
  runtime_vm_shared_directory: /vagrant/.runtime
region-config:
  regions: ["us-east"]
  k8s-cluster-for-platform-services:
    deploy:
      elb: true
      edns: false
      eca: false
      k8s_datastore: false
      k8s_master: true
      k8s_worker: false
    debug: false
    availability_zones_per_region: 3
    master_nodes_per_cluster: 3
    worker_nodes_per_cluster: 0
    ip_addresses_reserved_per_cluster: 5
  k8s-cluster-for-product-services:
    deploy:
      elb: true
      edns: false
      eca: false
      k8s_datastore: false
      k8s_master: true
      k8s_worker: false
    debug: false
    availability_zones_per_region: 3
    master_nodes_per_cluster: 3
    worker_nodes_per_cluster: 0
    ip_addresses_reserved_per_cluster: 5
elb-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 2048
      cpus: 1
  terraform-config:
edns-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 2048
      cpus: 1
  terraform-config:
    azure:
      deploy: false
    aws:
      deploy: false
    gcp:
      deploy: false
eca-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 2048
      cpus: 1
  terraform-config:
    azure:
      deploy: false
    aws:
      deploy: false
    gcp:
      deploy: false
k8s-datastore-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 4096
      cpus: 2
  terraform-config:
    azure:
      deploy: false
    aws:
      deploy: false
    gcp:
      deploy: false
k8s-master-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 4096
      cpus: 2
  terraform-config:
    azure:
      deploy: false
    aws:
      deploy: false
    gcp:
      deploy: false
k8s-worker-vm:
  vagrant-config:
    vagrant-box: ubuntu/focal64
    virtualbox:
      gui: true
      memory: 4096
      cpus: 2
  terraform-config:
    azure:
      deploy: false
    aws:
      deploy: false
    gcp:
      deploy: false